[language-server.angular-ls]
command = "ngserver"

args = [
  "--ngProbeLocations",
  "${$NODE_MODULES_GLOBAL}",
  "--tsProbeLocations",
  "${$NODE_MODULES_GLOBAL}",
  "--stdio",
  # If this for some reason doesn't work, try replacing ${NODE_MODULES_GLOBAL} with the absolute paths, e.g. output of `npm root -g`
]

file-types = ["ts", "typescript", "html"]

[[language]]
name = "typescript"
language-servers = ["angular-ls", "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "html"
language-servers = ["angular-ls", "vscode-html-language-server"]
formatter = { command = 'prettier', args = ["--parser", "angular"] }
auto-format = true
