import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

# - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
 # - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
#  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
#  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
#  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
 # - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word